# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Azusa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Azusa
  pod 'CocoaAsyncSocket' 

  target 'AzusaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AzusaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
